 INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES (1,'CORREO');
 INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES (2,'NUMERO');
 INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) VALUES (3,'DIRECCION');



 INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES (1,'CC');
 INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES (2,'CEDULA EXTRANJERA');
 INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC) VALUES (3,'PASAPORTE');

 

 INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (1,'PAIS');
 INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (2,'CIUDAD');
 INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (3,'JUZGADO');

 

 INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES (1,'EFECTIVO');
 INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES (2,'TARJETA');
 INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) VALUES (3,'BILLETERA MOVIL');

 

 INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES (1,'BANCOLOMBIA');
 INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES (2,'DAVIVIENDA');
 INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) VALUES (3,'BANCO DE BOGOTA');

 

 INSERT INTO INSTANCIA  (NINSTANCIA) VALUES (1);
 INSERT INTO INSTANCIA  (NINSTANCIA) VALUES (2);
 INSERT INTO INSTANCIA  (NINSTANCIA) VALUES (3);

 

 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (1, 'Indagacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (2, 'Imputacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (3, 'Acusacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (4, 'Juicio');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (5, 'Sentencia');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (6, 'Impugnacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (7, 'Demanda');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (8, 'Contestacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (9, 'Audiencia');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (10, 'Pruebas');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (11, 'Presentacion');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (12, 'Tramite urgente');
 INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) VALUES (13, 'Fallo');

 

 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (1, 'Reposicion');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (2, 'Apelacion');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (3, 'Casacion');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (4, 'Revision');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (5, 'Unificacion de jurisprudencia');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (6, 'Impugnacion de tutela');
 INSERT INTO IMPUGNACION (IDIMPUGNA, NOMIMPUGNA) VALUES (7, 'Revision constitucional');

 

 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (1, 'Penal');
 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (2, 'Civil');
 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (3, 'Laboral');
 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (4, 'Administrativo');
 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (5, 'Tutela');
 INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) VALUES (6, 'Familia');




 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (1, 1, 1, 1);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (1, 2, 1, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (1, 3, 1, 3);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (1, 4, 1, 4);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (1, 5, 1, 5);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (1, 6, 2, 6, 1);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (1, 7, 2, 6, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (1, 8, 3, 6, 3);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (1, 9, 3, 6, 4);

 

 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (2, 1, 1, 7);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (2, 2, 1, 8);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (2, 3, 1, 9);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (2, 4, 1, 10);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (2, 5, 1, 5);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (2, 6, 2, 6, 1);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (2, 7, 2, 6, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (2, 8, 2, 6, 3);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (2, 9, 2, 6, 4);

 

 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (3, 1, 1, 7);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (3, 2, 1, 9);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (3, 3, 1, 10);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (3, 4, 1, 5);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (3, 5, 2, 6, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (3, 6, 2, 6, 3);

 

 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (4, 1, 1, 7);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (4, 2, 1, 8);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (4, 3, 1, 10);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (4, 4, 1, 5);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (4, 5, 2, 6, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (4, 6, 2, 6, 4);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (4, 7, 2, 6, 5);

 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (5, 1, 1, 11);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (5, 2, 1, 12);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA) VALUES (5, 3, 1, 13);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (5, 4, 2, 6, 6);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (5, 5, 2, 6, 7);


 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (6, 1, 2, 6, 2);
 INSERT INTO ESPECIA_ETAPA (CODESPECIALIZACION, PASOETAPA, NINSTANCIA, CODETAPA, IDIMPUGNA) VALUES (6, 2, 2, 6, 3);

 


 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES (1, 1, 'MAURICIO', 'TABARES', 10146600402);
 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES (2, 2, 'SANTIAGO', 'ALDANA', 51923845);
 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES (3, 2, 'SANTIAGO', 'LUGO', 53528112);
 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES (4, 3, 'JUAN', 'QUIROGA', 10132830302);
 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES (5, 1, 'DANIELA', 'HERNANDEZ', 1330432);




 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (1011123, 'SERGIO', 'PORRAS', 58369);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (1058742, 'PAOLA', 'GONZALEZ', 12587);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (10747458, 'OSCAR', 'GONZALEZ', 48756);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (117486259, 'CAMILO', 'PEREZ', 65821);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (6285471, 'SOFIA', 'ALDANA', 24751);

 
 INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) VALUES (4,'JUZGADO');

 

 INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (34, 1, 'España');
 INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (1, 1, 'EEUU');
 INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (57, 1, 'Colombia');
 INSERT INTO LUGAR (CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (52, 1, 'Mexico');

 

 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (341, 34, 2, 'Madrid');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (11, 1, 2, 'Washington');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (571, 57, 2, 'Bogota');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR) VALUES (521, 52, 2, 'CDMX');

 

 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5711, 571, 3, 'Juzgado 1 Penal Municipal', 'Calle 19 #7-32', 6015554400, 'juzgado1penal@justicia.co');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (3411, 341, 3, 'Juzgado de 1 Instancia 5', 'Passeig de Gracia 80', 932555780, 'instancia5@justicia.es');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5211, 521, 3, 'Juzgado Civil Central de 1I', 'Av. Reforma 250', 5555501200, 'civilcentral@poderjudicial.mx');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (3412, 341,  4, 'Tribunal Supremo', 'Calle Justicia 12', 910555001, 'contacto@tribunalsupremo.es');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (111, 11,  4, 'Supreme Court of the US', '1 First St NE', 2025552100, 'info@supremecourt.us');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5712, 571,  4, 'Corte Suprema de Justicia', 'Carrera 8 #12-45', 6015559000, 'contacto@cortesuprema.co');

 

 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (7214598, 'MARIO', 'VELASQUEZ', 31842);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (8451267, 'LAURA', 'CASTRO', 28911);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL)  VALUES (9145723, 'CARLOS', 'TORRES', 30577);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (6578912, 'ANGELA', 'RAMIREZ', 27654);
 INSERT INTO ABOGADO (CEDULA, NOMBRE, APELLIDO, NTARJETAPROFESIONAL) VALUES (7823491, 'DIEGO', 'MARTINEZ', 33289);

 




 INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES ('C001', 1, 'Juan', 'Perez', 1020304050);
 INSERT INTO CONTACTO (CODCLIENTE, CONSECONTACTO, IDTIPOCONTA, VALORCONTACTO, NOTIFICACION) VALUES ('C001', 1, 2, '3001234567', TRUE);

 INSERT INTO ABOGADOESPEFK (CODESPECIALIZACION, CEDULA) VALUES (1, 1011123);
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5713, 571, 3, 'Juzgado Penal del Circuito', 'Av. Ciudad de Cali', 6015551122, 'juzgpenalcircuito@justicia.co');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5714, 571, 4, 'Tribunal Superior', 'Calle 20 #8-55', 6015553344, 'tribunalbogota@justicia.co');
 INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5715, 571, 4, 'Corte Constitucional', 'Palacio de Justicia', 6015556677, 'corteconstitucional@justicia.co');


 INSERT INTO CASO (NOCASO, CODESPECIALIZACION, CODCLIENTE, FECHAINICIO, FECHAFIN, VALOR) VALUES (1001, 1, 'C001', TO_DATE('2025-11-10', 'YYYY-MM-DD'), TO_DATE('2025-11-18', 'YYYY-MM-DD'), '2500000');


 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 1, 1001, 1, 1011123, 5711, TO_DATE('2025-11-10', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 2, 1001, 1, 1011123, 5711, TO_DATE('2025-11-11', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 3, 1001, 1, 1011123, 5711, TO_DATE('2025-11-12', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 4, 1001, 1, 1011123, 5711, TO_DATE('2025-11-13', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 5, 1001, 1, 1011123, 5713, TO_DATE('2025-11-14', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 7, 1001, 1, 1011123, 5714, TO_DATE('2025-11-16', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 8, 1001, 1, 1011123, 5712, TO_DATE('2025-11-17', 'YYYY-MM-DD'));
 INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 9, 1001, 1, 1011123, 5715, TO_DATE('2025-11-18', 'YYYY-MM-DD'));


 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 1, 1001, 1, 1, 'Fiscalia recopila pruebas (camaras, declaraciones). Abogado solicita pruebas favorables.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 1, 1001, 1, 1, 'Apertura de investigacion formal.');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 2, 1001, 1, 1, 'Audiencia ante Juez de Control de Garantias. Fiscal imputa Hurto Agravado.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 2, 1001, 1, 1, 'Juan Perez no acepta cargos.');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 3, 1001, 1, 1, 'Fiscal presenta escrito de acusacion. Defensa examina pruebas y prepara defensa tecnica.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 3, 1001, 1, 1, 'Se admite la acusación y se fija fecha de audiencia preparatoria.');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 4, 1001, 1, 1, 'Practica de pruebas, interrogatorios y alegatos finales.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL)VALUES (1, 5, 1001, 1, 1, 'Sentencia Condenatoria (Hipotetica, para poder apelar).');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 7, 1001, 1, 1, 'Abogado presenta recurso de apelacion ante Tribunal Superior.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL)VALUES (1, 7, 1001, 1, 1, 'Tribunal confirma la sentencia de primera instancia.');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 8, 1001, 1, 1, 'Abogado interpone recurso extraordinario de casacion ante Corte Suprema de Justicia.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 8, 1001, 1, 1, 'Corte Suprema inadmite el recurso de casación.');

 INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 9, 1001, 1, 1, 'Abogado presenta accion de tutela por vulneracion de derechos fundamentales.');
 INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 9, 1001, 1, 1, 'Corte Constitucional no selecciona la tutela para revisión.');

 INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 1, 1001, 1, 1, '/fiscalia/caso1001/informe_captura.pdf');
 INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 3, 1001, 1, 1, '/fiscalia/caso1001/escrito_acusacion.pdf');
 INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 5, 1001, 1, 1, '/juzgado/caso1001/sentencia_primera_instancia.pdf');



 


