SQL> INSERT INTO CLIENTE (CODCLIENTE, IDTIPODOC, NOMCLIENTE, APELCLIENTE, NDOCUMENTO) VALUES ('C001', 1, 'Juan', 'Perez', 1020304050);

1 fila creada.

SQL> INSERT INTO CONTACTO (CODCLIENTE, CONSECONTACTO, IDTIPOCONTA, VALORCONTACTO, NOTIFICACION) VALUES ('C001', 1, 2, '3001234567', TRUE);

1 fila creada.

SQL> INSERT INTO ABOGADOESPEFK (CODESPECIALIZACION, CEDULA) VALUES (1, 1011123);

1 fila creada.

SQL> INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5715, 571, 4, 'Corte Constitucional', 'Palacio de Justicia', 6015556677, 'corteconstitucional@justicia.co');

1 fila creada.

SQL> INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5713, 571, 3, 'Juzgado Penal del Circuito', 'Av. Ciudad de Cali', 6015551122, 'juzgpenalcircuito@justicia.co');

1 fila creada.

SQL> INSERT INTO LUGAR (CODLUGAR, LUG_CODLUGAR, IDTIPOLUGAR, NOMLUGAR, DIRELUGAR, TELLUGAR, EMAILLUGAR) VALUES (5714, 571, 4, 'Tribunal Superior', 'Calle 20 #8-55', 6015553344, 'tribunalbogota@justicia.co');

1 fila creada.

SQL> INSERT INTO CASO (NOCASO, CODESPECIALIZACION, CODCLIENTE, FECHAINICIO, FECHAFIN, VALOR) VALUES (1001, 1, 'C001', TO_DATE('2025-11-10', 'YYYY-MM-DD'), TO_DATE('2025-11-18', 'YYYY-MM-DD'), '2500000');

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 1, 1001, 1, 1011123, 5711, TO_DATE('2025-11-10', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 2, 1001, 1, 1011123, 5711, TO_DATE('2025-11-11', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 3, 1001, 1, 1011123, 5711, TO_DATE('2025-11-12', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 4, 1001, 1, 1011123, 5711, TO_DATE('2025-11-13', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 5, 1001, 1, 1011123, 5713, TO_DATE('2025-11-14', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 7, 1001, 1, 1011123, 5714, TO_DATE('2025-11-16', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 8, 1001, 1, 1011123, 5712, TO_DATE('2025-11-17', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO EXPEDIENTE (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CEDULA, CODLUGAR, FECHAETAPA) VALUES (1, 9, 1001, 1, 1011123, 5715, TO_DATE('2025-11-18', 'YYYY-MM-DD'));

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 1, 1001, 1, 1, 'Fiscalia recopila pruebas (camaras, declaraciones). Abogado solicita pruebas favorables.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 1, 1001, 1, 1, 'Apertura de investigacion formal.');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 2, 1001, 1, 1, 'Audiencia ante Juez de Control de Garantias. Fiscal imputa Hurto Agravado.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 2, 1001, 1, 1, 'Juan Perez no acepta cargos.');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO) VALUES (1, 3, 1001, 1, 1, 'Fiscal presenta escrito de acusacion. Defensa examina pruebas y prepara defensa tecnica.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 3, 1001, 1, 1, 'Se admite la acusación y se fija fecha de audiencia preparatoria.');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 4, 1001, 1, 1, 'Practica de pruebas, interrogatorios y alegatos finales.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL)VALUES (1, 5, 1001, 1, 1, 'Sentencia Condenatoria (Hipotetica, para poder apelar).');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 7, 1001, 1, 1, 'Abogado presenta recurso de apelacion ante Tribunal Superior.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL)VALUES (1, 7, 1001, 1, 1, 'Tribunal confirma la sentencia de primera instancia.');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 8, 1001, 1, 1, 'Abogado interpone recurso extraordinario de casacion ante Corte Suprema de Justicia.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 8, 1001, 1, 1, 'Corte Suprema inadmite el recurso de casación.');

1 fila creada.

SQL> INSERT INTO SUCESO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONSUCESO, DESCSUCESO)VALUES (1, 9, 1001, 1, 1, 'Abogado presenta accion de tutela por vulneracion de derechos fundamentales.');

1 fila creada.

SQL> INSERT INTO RESULTADO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONRESUL, DESCRESUL) VALUES (1, 9, 1001, 1, 1, 'Corte Constitucional no selecciona la tutela para revisión.');

1 fila creada.

SQL> INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 1, 1001, 1, 1, '/fiscalia/caso1001/informe_captura.pdf');

1 fila creada.

SQL> INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 3, 1001, 1, 1, '/fiscalia/caso1001/escrito_acusacion.pdf');

1 fila creada.

SQL> INSERT INTO DOCUMENTO (CODESPECIALIZACION, PASOETAPA, NOCASO, CONSECEXPE, CONDOC, UBICADOC)VALUES (1, 5, 1001, 1, 1, '/juzgado/caso1001/sentencia_primera_instancia.pdf');

1 fila creada.

SQL> spool off
